apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "dali-%s-pv" (include "hpcc-localfile.fullname" $) }}
  labels:
    type: local
    store: dali
spec:
  storageClassName: hostpath
  capacity:
    storage: {{ .Values.daliStorage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: Directory
    path: {{ .Values.daliStorage.hostpath | default (printf "%s/dali" .Values.common.hostpath) | required "Please specify hostpath" | quote }}
