apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "data-%s-pv" (include "hpcc-localfile.fullname" $) }}
  labels:
    type: local
    store: {{ printf "data-%s-pv" (include "hpcc-localfile.fullname" $) }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.dataStorage.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: Directory
    path: {{ .Values.dataStorage.hostpath | default (printf "%s/data" .Values.common.hostpath) | required "Please specify hostpath" | quote }}
