apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "data-%s-pvc" (include "hpcc-localfile.fullname" $) }}
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dataStorage.size }}
  selector:
    matchLabels:
      store: data
